# Generated by Django 5.1.7 on 2026-05-25 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_user_position'),
        ('stores', '0003_alter_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('EINVOICE_CREATED', 'E-Invoice Created'), ('EINVOICE_VERIFIED', 'E-Invoice Verified'), ('VAT_FILING_GENERATED', 'VAT Filing Generated'), ('TAX_FILING_APPROVED', 'Tax Filing Approved'), ('TAX_FILING_SUBMITTED', 'Tax Filing Submitted'), ('PERIOD_LOCKED', 'Period Locked')], max_length=50)),
                ('reference', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_tin', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vat_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('qr_code_payload', models.TextField(blank=True, null=True)),
                ('digital_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('VOIDED', 'Voided')], default='DRAFT', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_einvoices', to=settings.AUTH_USER_MODEL)),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='EInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_type', models.CharField(max_length=30)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='compliance.einvoice')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_period', models.CharField(max_length=20)),
                ('lock_type', models.CharField(choices=[('ACCOUNTING', 'Accounting'), ('VAT', 'VAT'), ('PAYROLL', 'Payroll'), ('FULL', 'Full Period Lock')], max_length=30)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_period_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('business_name', 'reporting_period', 'lock_type')},
            },
        ),
        migrations.CreateModel(
            name='TaxFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('VAT', 'VAT'), ('PAYE', 'PAYE'), ('WITHHOLDING', 'Withholding'), ('CORPORATE_INCOME_TAX', 'Corporate Income Tax')], max_length=50)),
                ('reporting_period', models.CharField(max_length=20)),
                ('total_taxable_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_exempt_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('output_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('input_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_tax_payable', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('lra_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_FOR_REVIEW', 'Ready For Review'), ('APPROVED', 'Approved'), ('SUBMITTED', 'Submitted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tax_filings', to=settings.AUTH_USER_MODEL)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
            options={
                'unique_together': {('business_name', 'tax_type', 'reporting_period')},
            },
        ),
    ]
