# Generated by Django 5.1.7 on 2026-05-27 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('customers', '0004_client_inventory_valuation_method'),
        ('stores', '0005_storeuserassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchVATSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_period', models.CharField(max_length=20)),
                ('taxable_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('exempt_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('zero_rated_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('output_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('input_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryComplianceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('STOCK_RECEIVED', 'Stock Received'), ('STOCK_SOLD', 'Stock Sold'), ('STOCK_TRANSFERRED', 'Stock Transferred'), ('STOCK_ADJUSTED', 'Stock Adjusted'), ('STOCK_WRITTEN_OFF', 'Stock Written Off'), ('NEGATIVE_STOCK_ATTEMPT', 'Negative Stock Attempt'), ('EXPIRED_STOCK_ATTEMPT', 'Expired Stock Attempt')], max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_compliant', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='POSComplianceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_reference', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('SALE_POSTED', 'Sale Posted'), ('SALE_REFUNDED', 'Sale Refunded'), ('RECEIPT_PRINTED', 'Receipt Printed'), ('VAT_POSTED', 'VAT Posted'), ('EINVOICE_ISSUED', 'E-Invoice Issued')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_compliant', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='complianceauditlog',
            old_name='business_name',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='einvoice',
            old_name='store_name',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='einvoice',
            old_name='business_name',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='periodlock',
            old_name='business_name',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='taxfiling',
            old_name='business_name',
            new_name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='periodlock',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taxfiling',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='complianceauditlog',
            name='module',
            field=models.CharField(choices=[('POS', 'POS'), ('INVENTORY', 'Inventory'), ('VAT', 'VAT'), ('ACCOUNTING', 'Accounting'), ('COMPLIANCE', 'Compliance')], default='COMPLIANCE', max_length=30),
        ),
        migrations.AddField(
            model_name='complianceauditlog',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store'),
        ),
        migrations.AddField(
            model_name='periodlock',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store'),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store'),
        ),
        migrations.AlterField(
            model_name='complianceauditlog',
            name='action_type',
            field=models.CharField(choices=[('EINVOICE_CREATED', 'E-Invoice Created'), ('EINVOICE_VERIFIED', 'E-Invoice Verified'), ('VAT_FILING_GENERATED', 'VAT Filing Generated'), ('TAX_FILING_APPROVED', 'Tax Filing Approved'), ('TAX_FILING_SUBMITTED', 'Tax Filing Submitted'), ('PERIOD_LOCKED', 'Period Locked'), ('POS_EVENT', 'POS Event'), ('INVENTORY_EVENT', 'Inventory Event'), ('VAT_EVENT', 'VAT Event')], max_length=50),
        ),
        migrations.AlterField(
            model_name='einvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_einvoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='einvoice',
            name='invoice_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='periodlock',
            name='lock_type',
            field=models.CharField(choices=[('ACCOUNTING', 'Accounting'), ('VAT', 'VAT'), ('POS', 'POS'), ('INVENTORY', 'Inventory'), ('PAYROLL', 'Payroll'), ('FULL', 'Full Period Lock')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='einvoice',
            unique_together={('tenant', 'store', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='periodlock',
            unique_together={('tenant', 'store', 'reporting_period', 'lock_type')},
        ),
        migrations.AlterUniqueTogether(
            name='taxfiling',
            unique_together={('tenant', 'store', 'tax_type', 'reporting_period')},
        ),
        migrations.AddIndex(
            model_name='complianceauditlog',
            index=models.Index(fields=['tenant', 'store'], name='compliance__tenant__33c443_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceauditlog',
            index=models.Index(fields=['module', 'action_type'], name='compliance__module_8e014e_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceauditlog',
            index=models.Index(fields=['reference'], name='compliance__referen_29a4ba_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceauditlog',
            index=models.Index(fields=['created_at'], name='compliance__created_791d89_idx'),
        ),
        migrations.AddIndex(
            model_name='einvoice',
            index=models.Index(fields=['tenant', 'store'], name='compliance__tenant__9ea8a1_idx'),
        ),
        migrations.AddIndex(
            model_name='einvoice',
            index=models.Index(fields=['invoice_number'], name='compliance__invoice_6e609a_idx'),
        ),
        migrations.AddIndex(
            model_name='einvoice',
            index=models.Index(fields=['status'], name='compliance__status_0dbe98_idx'),
        ),
        migrations.AddIndex(
            model_name='periodlock',
            index=models.Index(fields=['tenant', 'store'], name='compliance__tenant__ef3d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='periodlock',
            index=models.Index(fields=['reporting_period', 'lock_type'], name='compliance__reporti_80f4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='periodlock',
            index=models.Index(fields=['is_locked'], name='compliance__is_lock_4f1681_idx'),
        ),
        migrations.AddIndex(
            model_name='taxfiling',
            index=models.Index(fields=['tenant', 'store'], name='compliance__tenant__7a06af_idx'),
        ),
        migrations.AddIndex(
            model_name='taxfiling',
            index=models.Index(fields=['tax_type', 'reporting_period'], name='compliance__tax_typ_2bb091_idx'),
        ),
        migrations.AddIndex(
            model_name='taxfiling',
            index=models.Index(fields=['status'], name='compliance__status_14f74a_idx'),
        ),
        migrations.AddField(
            model_name='branchvatsummary',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='branchvatsummary',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
        ),
        migrations.AddField(
            model_name='inventorycomplianceevent',
            name='destination_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_inventory_compliance_events', to='stores.store'),
        ),
        migrations.AddField(
            model_name='inventorycomplianceevent',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorycomplianceevent',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_compliance_events', to='stores.store'),
        ),
        migrations.AddField(
            model_name='inventorycomplianceevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
        ),
        migrations.AddField(
            model_name='poscomplianceevent',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poscomplianceevent',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='poscomplianceevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
        ),
        migrations.AddIndex(
            model_name='branchvatsummary',
            index=models.Index(fields=['tenant', 'store', 'reporting_period'], name='compliance__tenant__c1eaaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchvatsummary',
            unique_together={('tenant', 'store', 'reporting_period')},
        ),
    ]
