# Generated by Django 5.1.7 on 2026-06-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_branchvatsummary_inventorycomplianceevent_and_more'),
        ('customers', '0004_client_inventory_valuation_method'),
        ('stores', '0006_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceTaxLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('VAT', 'VAT'), ('PAYE', 'PAYE'), ('WITHHOLDING', 'Withholding Tax'), ('CORPORATE_INCOME', 'Corporate Income Tax')], max_length=50)),
                ('reference', models.CharField(max_length=100)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('period_month', models.CharField(max_length=20)),
                ('period_year', models.IntegerField()),
                ('status', models.CharField(choices=[('PAYABLE', 'Payable'), ('FILED', 'Filed'), ('PAID', 'Paid')], default='PAYABLE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_tax_ledgers', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_tax_ledgers', to='customers.client')),
            ],
            options={
                'unique_together': {('tenant', 'tax_type', 'reference')},
            },
        ),
    ]
