name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main   # deploy when pushing to main branch

jobs:
  deploy:
    name: Build & Deploy to App Runner
    runs-on: ubuntu-latest

    steps:
      # --- CHECKOUT REPO ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- CONFIGURE PYTHON (OPTIONAL: for tests, collectstatic before deploy) ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Run tests before deploy
      - name: Run tests
        run: |
          python manage.py check
          python manage.py test || true  # don't block deploy if tests fail (can remove `|| true` to enforce)

      # --- CONFIGURE AWS CREDENTIALS ---
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # --- DEPLOY TO APP RUNNER ---
      - name: Deploy to App Runner
        run: |
          aws apprunner start-deployment \
            --service-arn arn:aws:apprunner:us-east-1:192933325876:service/ledger-api/7511147e3cf747c19f7ca5f4e4ee4417
