name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to App Runner
    runs-on: ubuntu-latest

    steps:
      # --- CHECKOUT REPO ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- SET UP PYTHON ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --- INSTALL DEPENDENCIES ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- DJANGO CHECK ---
      - name: Check Django project
        run: python manage.py check

      # --- RUN MIGRATIONS ---
      - name: Run Django migrations
        run: |
          python manage.py migrate_schemas --shared --noinput
          python manage.py migrate_schemas --tenant --noinput

      # --- CREATE PUBLIC TENANT & DOMAIN ---
      - name: Ensure public tenant and domain
        run: python manage.py setup_public_domain

      # --- COLLECT STATIC FILES ---
      - name: Collect static files
        run: python manage.py collectstatic --noinput

      # --- DEPLOY TO APP RUNNER ---
      - name: Deploy to App Runner
        run: |
          aws apprunner start-deployment \
            --service-arn arn:aws:apprunner:us-east-1:192933325876:service/ledger-api/7511147e3cf747c19f7ca5f4e4ee4417
