# Generated by Django 5.1.7 on 2026-05-26 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_client_inventory_valuation_method'),
        ('ledger', '0002_alter_journalentry_created_by'),
        ('stores', '0004_store_branch_code_store_is_main_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='customers.client'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('tenant', 'code')},
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='business_name',
        ),

        migrations.AddField(
            model_name='journalentry',
            name='destination_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_inter_store_entries', to='stores.store'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_inter_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_inter_store_entries', to='stores.store'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='stores.store'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='customers.client'),
        ),
        migrations.RemoveField(
            model_name='account',
            name='business_name',
        ),
    ]
