# Generated by Django 5.1.7 on 2026-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_account_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='cash_flow_category',
            field=models.CharField(blank=True, choices=[('OPERATING', 'Operating'), ('INVESTING', 'Investing'), ('FINANCING', 'Financing')], max_length=20, null=True),
        ),
    ]
