# Generated by Django 5.1.7 on 2026-05-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_journalentry_cash_flow_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reconciliation_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalline',
            name='reconciliation_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
