# Generated by Django 5.1.7 on 2026-05-26 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_journalentry_is_reconciled_and_more'),
        ('stores', '0005_storeuserassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='stores.store'),
        ),
    ]
