branch-defaults:
  main:
    environment: Ledger-API-env 
    group_suffix: null
environment-defaults:
  Ledger-API-env:
    branch: null
    repository: null
global:
  application_name: ledgerAPI
  branch: null
  default_ec2_keyname: ledger test
  default_platform: Python 3.13
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
