# Generated by Django 5.1.7 on 2026-05-25 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_user_position'),
        ('inventory', '0018_remove_stockrequest_quantity_requested_and_more'),
        ('sales', '0028_sale_subtotal_sale_vat_total_saledetail_subtotal_and_more'),
        ('stores', '0003_alter_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReconciliationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('BANK', 'Bank'), ('MOMO', 'Mobile Money')], max_length=30)),
                ('matching_reference', models.BooleanField(default=True)),
                ('matching_amount', models.BooleanField(default=True)),
                ('matching_date', models.BooleanField(default=False)),
                ('auto_approve', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'unique_together': {('business_name', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bank-statements/')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=255, unique=True)),
                ('settlement_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('settlement_batch', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('settlement_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('base_currency_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('transaction_date', models.DateField()),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='reconciliation.bankaccount')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ORANGE', 'Orange Money'), ('MTN', 'MTN Mobile Money')], max_length=30)),
                ('transaction_reference', models.CharField(max_length=255, unique=True)),
                ('settlement_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('settlement_batch', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('base_currency_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('settlement_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('transaction_date', models.DateTimeField()),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('matched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_partial_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momo_transactions', to='sales.sale')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='MT940Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='mt940/')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('UNUSUAL_AMOUNT', 'Unusual Amount'), ('DUPLICATE_PATTERN', 'Duplicate Pattern'), ('HIGH_VARIANCE', 'High Variance'), ('SUSPICIOUS_REVERSAL', 'Suspicious Reversal')], max_length=50)),
                ('reference', models.CharField(max_length=255)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_type', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=255)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('BANK_MISMATCH', 'Bank Mismatch'), ('MOMO_MISMATCH', 'MoMo Mismatch'), ('VAT_VARIANCE', 'VAT Variance'), ('DUPLICATE_PAYMENT', 'Duplicate Payment')], max_length=50)),
                ('reference', models.CharField(max_length=255)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierVATReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_invoice_number', models.CharField(max_length=255)),
                ('supplier_vat_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('system_vat_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MISMATCH', 'Mismatch'), ('PENDING', 'Pending')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
