# Generated by Django 5.1.7 on 2026-05-27 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_client_inventory_valuation_method'),
        ('inventory', '0019_rename_business_name_inventorymovement_tenant_and_more'),
        ('reconciliation', '0001_initial'),
        ('sales', '0028_sale_subtotal_sale_vat_total_saledetail_subtotal_and_more'),
        ('stores', '0005_storeuserassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='bankstatementimport',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='bankstatementimport',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='reconciled_by',
        ),
        migrations.RemoveField(
            model_name='mt940import',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='reconciliationanomaly',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='reconciliationapproval',
            name='approved_by',
        ),
        migrations.RenameField(
            model_name='mobilemoneytransaction',
            old_name='store_name',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='mobilemoneytransaction',
            old_name='business_name',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='reconciliationexception',
            old_name='business_name',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='suppliervatreconciliation',
            old_name='supplier_vat_amount',
            new_name='actual_vat_amount',
        ),
        migrations.RenameField(
            model_name='suppliervatreconciliation',
            old_name='system_vat_amount',
            new_name='expected_vat_amount',
        ),
        migrations.RenameField(
            model_name='suppliervatreconciliation',
            old_name='created_at',
            new_name='reconciled_at',
        ),
        migrations.RemoveField(
            model_name='mobilemoneytransaction',
            name='base_currency_amount',
        ),
        migrations.RemoveField(
            model_name='mobilemoneytransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='mobilemoneytransaction',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='mobilemoneytransaction',
            name='settlement_batch',
        ),
        migrations.RemoveField(
            model_name='mobilemoneytransaction',
            name='settlement_date',
        ),
        migrations.RemoveField(
            model_name='mobilemoneytransaction',
            name='settlement_fee',
        ),
        migrations.RemoveField(
            model_name='mobilemoneytransaction',
            name='settlement_reference',
        ),
        migrations.RemoveField(
            model_name='suppliervatreconciliation',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='suppliervatreconciliation',
            name='supplier_invoice_number',
        ),
        migrations.AddField(
            model_name='reconciliationexception',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='suppliervatreconciliation',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliervatreconciliation',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliervatreconciliation',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobilemoneytransaction',
            name='customer_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationexception',
            name='exception_type',
            field=models.CharField(choices=[('CASH_SHORTAGE', 'Cash Shortage'), ('CASH_OVERAGE', 'Cash Overage'), ('MOMO_MISMATCH', 'Mobile Money Mismatch'), ('VAT_VARIANCE', 'VAT Variance')], max_length=50),
        ),
        migrations.CreateModel(
            name='CashReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('system_cash_sales', models.DecimalField(decimal_places=2, max_digits=18)),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('SHORTAGE', 'Shortage'), ('OVERAGE', 'Overage')], max_length=30)),
                ('shift_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_reconciliations_done', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_reference', models.CharField(max_length=255, unique=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='reconciliation.cashreconciliation')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='sales.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='MobileMoneyReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MISMATCH', 'Mismatch'), ('PENDING', 'Pending')], default='PENDING', max_length=30)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('momo_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='reconciliation.mobilemoneytransaction')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momo_reconciliations', to='sales.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierVATTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_invoice_number', models.CharField(max_length=255)),
                ('supplier_vat_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_vat_transactions', to='inventory.purchase')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
        migrations.AddField(
            model_name='suppliervatreconciliation',
            name='supplier_vat_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='reconciliation.suppliervattransaction'),
        ),
        migrations.DeleteModel(
            name='AutoReconciliationRule',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='BankStatementImport',
        ),
        migrations.DeleteModel(
            name='BankTransaction',
        ),
        migrations.DeleteModel(
            name='MT940Import',
        ),
        migrations.DeleteModel(
            name='ReconciliationAnomaly',
        ),
        migrations.DeleteModel(
            name='ReconciliationApproval',
        ),
    ]
