# Generated by Django 5.1.7 on 2026-06-01 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_compliancetaxledger'),
        ('customers', '0004_client_inventory_valuation_method'),
        ('payroll', '0002_remove_employee_business_name_remove_employee_email_and_more'),
        ('reconciliation', '0002_alter_bankaccount_unique_together_and_more'),
        ('sales', '0029_sale_is_posted_sale_status_alter_sale_payment_status'),
        ('stores', '0006_delete_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PAYROLL_PAYMENT', 'Payroll Payment'), ('PAYE_PAYMENT', 'PAYE Payment')], default='SALE', max_length=50),
        ),
        migrations.AddField(
            model_name='mobilemoneytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PAYROLL_PAYMENT', 'Payroll Payment'), ('PAYE_PAYMENT', 'PAYE Payment')], default='SALE', max_length=50),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='sales.sale'),
        ),
        migrations.CreateModel(
            name='PAYEPaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money')], max_length=30)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MISMATCH', 'Mismatch'), ('PARTIAL', 'Partial')], max_length=30)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('cash_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconciliation.cashtransaction')),
                ('compliance_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paye_payment_reconciliations', to='compliance.compliancetaxledger')),
                ('mobile_money_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconciliation.mobilemoneytransaction')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money')], max_length=30)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MISMATCH', 'Mismatch'), ('PARTIAL', 'Partial')], max_length=30)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('cash_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconciliation.cashtransaction')),
                ('mobile_money_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconciliation.mobilemoneytransaction')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reconciliations', to='payroll.payrollrun')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
    ]
