# Generated by Django 5.1.7 on 2026-05-25 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_user_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('VAT_ANOMALY', 'VAT Anomaly'), ('REFUND_RISK', 'Refund Risk'), ('PAYROLL_ANOMALY', 'Payroll Anomaly'), ('SALES_PATTERN', 'Sales Pattern'), ('FILING_OVERDUE', 'Filing Overdue'), ('RECONCILIATION_RISK', 'Reconciliation Risk'), ('FRAUD_RISK', 'Fraud Risk')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('FULL', 'Full Compliance Analysis'), ('VAT', 'VAT Analysis'), ('PAYROLL', 'Payroll Analysis'), ('SALES', 'Sales Analysis'), ('FRAUD', 'Fraud Analysis')], max_length=30)),
                ('reporting_period', models.CharField(blank=True, max_length=20, null=True)),
                ('total_alerts', models.IntegerField(default=0)),
                ('highest_risk_level', models.CharField(default='LOW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
    ]
