# Generated by Django 5.1.7 on 2025-03-24 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.lot'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='customers.client'),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='productsection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='productsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.section'),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='from_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_from', to='inventory.section'),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='to_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_to', to='inventory.section'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.section'),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='products.product'),
        ),
    ]
