# Generated by Django 5.1.7 on 2025-07-13 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_warehouse_warehouse_uuid_alter_stockrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
