# Generated by Django 5.1.6 on 2025-08-04 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_updated_at'),
        ('products', '0007_remove_lot_product_remove_productattribute_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.productlot'),
        ),
    ]
