# Generated by Django 5.1.6 on 2025-08-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_quantity'),
        ('products', '0010_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.productvariant'),
        ),
    ]
