# Generated by Django 5.1.6 on 2025-08-05 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0010_inventory_product_variant'),
        ('products', '0010_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('tenant', 'warehouse', 'section', 'product', 'product_variant')},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='lot',
        ),
    ]
