# Generated by Django 5.1.6 on 2025-08-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventory_unique_together_remove_inventory_lot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
    ]
