# Generated by Django 5.1.6 on 2025-08-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventory_unique_together'),
        ('products', '0010_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productlot'),
        ),
    ]
