# Generated by Django 5.1.6 on 2025-08-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0013_inventory_lot'),
        ('products', '0010_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('tenant', 'warehouse', 'section', 'product', 'product_variant', 'lot'), name='unique_inventory_per_lot'),
        ),
    ]
