# Generated by Django 5.1.6 on 2025-08-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventory_unique_inventory_per_lot'),
        ('products', '0010_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_inventory_per_lot',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='inventory_i_product_f6b65e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('lot', 'warehouse', 'section')},
        ),
    ]
