# Generated by Django 5.1.6 on 2025-08-06 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0015_remove_inventory_unique_inventory_per_lot_and_more'),
        ('products', '0010_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.CharField(choices=[('to_store', 'To Store'), ('to_general', 'To General')], max_length=20)),
                ('destination_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='inventory.inventory')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productlot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
                ('source_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='inventory.inventory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferlogs', to='customers.client')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductMovement',
        ),
    ]
