# Generated by Django 5.1.7 on 2025-09-12 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0016_transferlog_delete_productmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transfers', to='customers.user'),
        ),
    ]
