# Generated by Django 5.1.7 on 2026-05-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_user_position'),
        ('inventory', '0017_alter_transfer_confirmed_by'),
        ('products', '0014_product_average_cost'),
        ('sales', '0028_sale_subtotal_sale_vat_total_saledetail_subtotal_and_more'),
        ('stores', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrequest',
            name='quantity_requested',
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry_id', models.UUIDField(blank=True, null=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reference', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry_id', models.UUIDField(blank=True, null=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productlot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.productvariant')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='sales.sale')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='inventory.transfer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='inventory.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tin', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('vat_registered', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='customers.client')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('business_name', 'invoice_number')},
        ),
    ]
