# Generated by Django 5.1.7 on 2026-05-26 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_client_inventory_valuation_method'),
        ('inventory', '0018_remove_stockrequest_quantity_requested_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymovement',
            old_name='business_name',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='business_name',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='business_name',
            new_name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('tenant', 'invoice_number')},
        ),
    ]
