# Generated by Django 5.1.6 on 2025-03-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('domain_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
