# Generated by Django 5.1.7 on 2026-05-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_first_name_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Cashier', 'Cashier'), ('ACCOUNTANT', 'Accountant'), ('AUDITOR', 'Auditor')], default='Admin', max_length=50),
        ),
    ]
