# Generated by Django 5.1.7 on 2026-05-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='inventory_valuation_method',
            field=models.CharField(choices=[('AVG_COST', 'Average Cost'), ('FIFO', 'FIFO')], default='AVG_COST', max_length=20),
        ),
    ]
