# Generated by Django 5.1.7 on 2026-05-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tax_type', models.CharField(choices=[('VATABLE', 'Vatable'), ('EXEMPT', 'Exempt'), ('ZERO_RATED', 'Zero Rated')], max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='VATLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_type', models.CharField(choices=[('INPUT', 'Input'), ('OUTPUT', 'Output')], max_length=20)),
                ('transaction_reference', models.CharField(max_length=255)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reporting_period', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
    ]
