# Generated by Django 5.1.7 on 2026-06-01 13:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_client_inventory_valuation_method'),
        ('stores', '0006_delete_employee'),
        ('taxation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreVATSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('input_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('adjustment_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_vat_payable', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH', 'Cash'), ('OTHER', 'Other')], max_length=30)),
                ('transaction_reference', models.CharField(max_length=255)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('STORE_REVIEW', 'Store Review'), ('ADMIN_REVIEW', 'Admin Review'), ('APPROVED', 'Approved'), ('FILED', 'Filed'), ('LOCKED', 'Locked')], default='OPEN', max_length=30)),
                ('is_locked', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VATAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('INCREASE_OUTPUT', 'Increase Output VAT'), ('DECREASE_OUTPUT', 'Decrease Output VAT'), ('INCREASE_INPUT', 'Increase Input VAT'), ('DECREASE_INPUT', 'Decrease Input VAT')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VATReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_output_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_input_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_adjustment_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_vat_payable', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('carried_forward_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('FILED', 'Filed'), ('PAID', 'Paid')], default='DRAFT', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('filing_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='taxclass',
            options={'ordering': ['code']},
        ),

        migrations.RemoveField(
            model_name='vatledger',
            name='business_name',
        ),
        migrations.AddField(
            model_name='taxclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,  default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxclass',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tax_classes', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vatledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatledger',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vatledger',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vatledger',
            name='source_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('RETURN', 'Return'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')],  default='SALE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vatledger',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_ledgers', to='stores.store'),
        ),
        migrations.AddField(
            model_name='vatledger',
            name='tax_type',
            field=models.CharField(choices=[('VATABLE', 'Vatable'), ('EXEMPT', 'Exempt'), ('ZERO_RATED', 'Zero Rated')], default='VATABLE', max_length=30),
        ),
        migrations.AddField(
            model_name='vatledger',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vat_ledgers', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxclass',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taxclass',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='vatledger',
            name='vat_type',
            field=models.CharField(choices=[('INPUT', 'Input VAT'), ('OUTPUT', 'Output VAT'), ('ADJUSTMENT', 'Adjustment')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='vatledger',
            index=models.Index(fields=['tenant', 'store'], name='taxation_va_tenant__1bacd0_idx'),
        ),
        migrations.AddIndex(
            model_name='vatledger',
            index=models.Index(fields=['tenant', 'reporting_period'], name='taxation_va_tenant__5fb66e_idx'),
        ),
        migrations.AddIndex(
            model_name='vatledger',
            index=models.Index(fields=['transaction_reference'], name='taxation_va_transac_9300c0_idx'),
        ),
        migrations.AddIndex(
            model_name='vatledger',
            index=models.Index(fields=['vat_type'], name='taxation_va_vat_typ_2fce67_idx'),
        ),
        migrations.AddField(
            model_name='storevatsummary',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_store_vat_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storevatsummary',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_summaries', to='stores.store'),
        ),
        migrations.AddField(
            model_name='storevatsummary',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_store_vat_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storevatsummary',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_vat_summaries', to='customers.client'),
        ),
        migrations.AddField(
            model_name='taxpayment',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxpayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
        ),
        migrations.AddField(
            model_name='taxperiod',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tax_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxperiod',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_tax_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxperiod',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_periods', to='customers.client'),
        ),
        migrations.AddField(
            model_name='storevatsummary',
            name='tax_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_summaries', to='taxation.taxperiod'),
        ),
        migrations.AddField(
            model_name='vatadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vat_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatadjustment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatadjustment',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store'),
        ),
        migrations.AddField(
            model_name='vatadjustment',
            name='tax_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxation.taxperiod'),
        ),
        migrations.AddField(
            model_name='vatadjustment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vat_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='filed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_vat_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='tax_period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vat_return', to='taxation.taxperiod'),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_returns', to='customers.client'),
        ),
        migrations.AddField(
            model_name='taxpayment',
            name='vat_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='taxation.vatreturn'),
        ),
        migrations.RemoveField(
            model_name='taxclass',
            name='business_name',
        ),
        migrations.AlterUniqueTogether(
            name='taxperiod',
            unique_together={('tenant', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='storevatsummary',
            unique_together={('tenant', 'store', 'tax_period')},
        ),
        migrations.AlterUniqueTogether(
            name='taxclass',
            unique_together={('tenant', 'code')},
        ),
    ]
