# Generated by Django 5.1.7 on 2026-06-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxation', '0002_storevatsummary_taxpayment_taxperiod_vatadjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatledger',
            name='source_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('RETURN', 'Return'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], max_length=30),
        ),
    ]
