# Generated by Django 5.0.8 on 2025-03-04 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='parent_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tenants', to='customers.client'),
        ),
    ]
