# Generated by Django 5.0.8 on 2025-03-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_stores_parent_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='parent_tenant',
        ),
    ]
