# Generated by Django 5.0.8 on 2025-03-06 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_stores_parent_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stores',
        ),
    ]
