# Generated by Django 5.1.7 on 2025-06-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
