# Generated by Django 5.1.7 on 2026-05-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_client_inventory_valuation_method'),
        ('stores', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='branch_code',
            field=models.CharField(blank=True, help_text='Unique accounting branch/store code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='is_main_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('tenant', 'branch_code')},
        ),
    ]
