# Generated by Django 5.1.7 on 2026-05-26 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_client_inventory_valuation_method'),
        ('stores', '0004_store_branch_code_store_is_main_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreUserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Cashier', 'Cashier'), ('ACCOUNTANT', 'Accountant'), ('AUDITOR', 'Auditor')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
            options={
                'unique_together': {('tenant', 'store', 'user_id')},
            },
        ),
    ]
