# Generated by Django 5.1.7 on 2026-06-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_storeuserassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
