# Generated by Django 5.1.6 on 2025-07-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_lot_retail_discount_price_and_more'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saledetail',
            old_name='quantity',
            new_name='quantity_sold',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.AddField(
            model_name='saledetail',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.lot'),
        ),
    ]
