# Generated by Django 5.1.6 on 2025-07-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_quantity_saledetail_quantity_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity_sold',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_price',
        ),
    ]
