# Generated by Django 5.1.6 on 2025-07-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_product_remove_sale_quantity_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
