# Generated by Django 5.1.6 on 2025-07-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_cashier_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Orange_Money', 'Orange Money'), ('Mobile_Money', 'Mobile Money'), ('Visa_MasterCard', 'Visa/MasterCard')], default='Cash', max_length=20),
        ),
    ]
