# Generated by Django 5.1.6 on 2025-07-25 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('LRD', 'Liberian Dollars')], default='LRD', max_length=3),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('LRD', 'LRD')], default='LRD', max_length=3),
        ),
        migrations.AddField(
            model_name='sale',
            name='exchange_rate',
            field=models.ForeignKey(blank=True, help_text='Applicable exchange rate for this sale if currency is LRD.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.exchangerate'),
        ),
    ]
