# Generated by Django 5.1.6 on 2025-07-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_exchangerate_sale_currency_saledetail_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='sale',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_lrd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('LRD', 'LRD')], default='USD', max_length=3),
        ),
    ]
