# Generated by Django 5.1.6 on 2025-07-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0010_remove_sale_exchange_rate_sale_exchange_rate_used_and_more'),
        ('stores', '0002_rename_location_store_address_store_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-effective_date']},
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='customers.client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customers.client'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='customers.client'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('tenant', 'effective_date')},
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('tenant', 'store', 'receipt_number')},
        ),
    ]
