# Generated by Django 5.1.6 on 2025-07-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_exchangerate_options_exchangerate_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='tenant',
        ),
    ]
