# Generated by Django 5.1.6 on 2025-07-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_exchangerate_tenant_alter_sale_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='currency',
        ),
    ]
