# Generated by Django 5.1.6 on 2025-07-25 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_remove_saledetail_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='saledetail',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('LRD', 'LRD')], default='LRD', max_length=3),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Orange_Money', 'Orange Money'), ('Mobile_Money', 'Mobile Money'), ('Visa_MasterCard', 'Visa/MasterCard')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('LRD', 'LRD')], max_length=3)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('refunded', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
        ),
    ]
