# Generated by Django 5.1.6 on 2025-07-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_rename_refund_amount_payment_refunded_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
    ]
