# Generated by Django 5.1.6 on 2025-08-04 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_lot_product_remove_productattribute_product_and_more'),
        ('sales', '0020_sale_balance_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productlot'),
        ),
    ]
