# Generated by Django 5.1.6 on 2025-08-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_saledetail_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='currency',
        ),
    ]
