# Generated by Django 5.1.7 on 2025-08-06 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_unique_together_and_more'),
        ('sales', '0022_remove_saledetail_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
    ]
