# Generated by Django 5.1.7 on 2025-08-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('sales', '0023_saledetail_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='order.order'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderitem'),
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
