# Generated by Django 5.1.7 on 2025-09-12 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0024_sale_order_saledetail_order_item_delete_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.user'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.user'),
        ),
        migrations.AlterField(
            model_name='salecancellationlog',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.user'),
        ),
    ]
