# Generated by Django 5.1.7 on 2026-02-15 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_first_name_user_full_name_and_more'),
        ('sales', '0025_alter_refund_processed_by_alter_sale_cashier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMonthlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'year', 'month'], name='sales_dashb_tenant__4e86d4_idx')],
                'unique_together': {('tenant', 'year', 'month')},
            },
        ),
    ]
