# Generated by Django 5.1.7 on 2026-02-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_dashboardmonthlystat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stats_applied',
            field=models.BooleanField(default=False),
        ),
    ]
