# Generated by Django 5.1.7 on 2025-03-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_discount_remove_lot_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.lot'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='products.product'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product'),
        ),
    ]
