# Generated by Django 5.1.6 on 2025-07-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_lot_retail_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('LRD', 'Liberian Dollars')], default='LRD', max_length=3),
        ),
    ]
