# Generated by Django 5.1.6 on 2025-07-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='retail_purchase_price',
            new_name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='wholesale_purchase_price',
        ),
    ]
