# Generated by Django 5.1.6 on 2025-08-04 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_retail_purchase_price_lot_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=50, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('wholesale_quantity', models.PositiveIntegerField(default=0)),
                ('wholesale_selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('retail_selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.productvariant')),
            ],
        ),
    ]
