# Generated by Django 5.1.6 on 2025-08-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventory_lot'),
        ('products', '0007_remove_lot_product_remove_productattribute_product_and_more'),
        ('sales', '0021_alter_saledetail_lot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lot',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.AlterUniqueTogether(
            name='variantattribute',
            unique_together={('variant', 'name')},
        ),
    ]
