# Generated by Django 5.1.6 on 2025-08-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_lot_delete_productattribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
    ]
