# Generated by Django 5.1.6 on 2025-08-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0009_remove_productvariant_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'product_name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='productlot',
            unique_together={('variant', 'lot_number')},
        ),
    ]
