# Generated by Django 5.1.7 on 2025-09-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/'),
        ),
    ]
