# Generated by Django 5.1.7 on 2025-10-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_transfer_confirmed_by'),
        ('products', '0011_productvariant_variant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlot',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
    ]
