# Generated by Django 5.1.7 on 2025-10-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_transfer_confirmed_by'),
        ('products', '0012_productlot_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlot',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.warehouse'),
        ),
    ]
