# Generated by Django 5.1.7 on 2026-06-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_rename_business_name_inventorymovement_tenant_and_more'),
        ('products', '0014_product_average_cost'),
        ('taxation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='taxation.taxclass'),
        ),
        migrations.AddField(
            model_name='productlot',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='inventory.purchaseitem'),
        ),
    ]
